routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('sitemap.xml', 'ArticlesController@sitemap')->name('sitemap');

//Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::post('ulogin', 'UloginController@login');

Route::group([
    'prefix' => 'admin',
    'middleware' => ['auth', 'IsAdmin'],
    'namespace' => 'Admin',
    'as' => 'admin.',
], function () {
    Route::get('/', 'IndexController@index')->name('index');

    Route::get('/ajax/yad/visits', 'IndexController@yadVisits')->name('yad.visits');

    Route::resource('comments', 'CommentController');

    Route::get('/users', 'UserController@index')->name('users.index');
    Route::get('/users/{user}/edit', 'UserController@edit')->name('users.edit');
    Route::put('/users/{user}', 'UserController@update')->name('users.update');

    Route::get('/tasks', 'TasksController@index')->name('tasks');
    Route::get('/tasks/list', 'TasksController@taskList')->name('tasks.list');
    Route::post('/tasks/add', 'TasksController@create')->name('tasks.create');
    Route::get('/tasks/start/{id}', 'TasksController@start')->name('tasks.start');
    Route::get('/tasks/stop/{id}', 'TasksController@stop')->name('tasks.stop');
    Route::get('/tasks/finish/{id}', 'TasksController@finish')->name('tasks.finish');
    Route::get('/tasks/delete/{id}', 'TasksController@delete')->name('tasks.delete');
    Route::put('/tasks', 'TasksController@create')->name('tasks.update');


    Route::get('/keys', 'IndexController@keys')->name('keys');
    Route::resource('news', 'NewsController');
    Route::resource('articles', 'ArticlesController');
    Route::resource('categories', 'CategoriesController');

    Route::post('upload-image', 'AjaxController@loadImage')->name('admin.ajax.load-image');
});

Route::get('/', 'ArticlesController@index')->name('index');
Route::get('/{category}/{article}.html', 'ArticlesController@article')->name('article');
Route::post('/comment/store', 'CommentController@store')->name('comment.add');


Route::get('/poisk', 'ArticlesController@search')->name('search');
Route::get('/o-nas', 'ArticlesController@aboutUs')->name('about-us');

Route::get('/{category}', 'ArticlesController@category')->name('category');

app/Models/Comment.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = ['body'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function article()
    {
        return $this->belongsTo(Articles::class, 'commentable_id');
    }
}

app/Http/Controllers/Admin/CommentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Comment;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CommentController extends Controller
{
    public function index() {
        return view('admin.comments.index', [
            'comments' => Comment::orderBy('created_at', 'DESC')->get()
        ]);
    }

    public function destroy($id)
    {
        Comment::find($id)->delete();

        return redirect()->route('admin.comments.index')
            ->with('success','Комментарий удален');
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Articles;
use App\Models\Comment;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    public function store(Request $request)
    {
        $comment = new Comment;
        $comment->body = $request->get('body');
        $comment->user()->associate($request->user());
        $article = Articles::find($request->get('model_id'));
        $article->comments()->save($comment);

        return redirect(redirect()->getUrlGenerator()->previous().'#comments');
    }
}

resources/views/admin/comments/index.blade.php
@extends('layouts.admin')

@section('content')

    @include('admin.title', [
        'title' => 'Комментарии',
        'items' => [
            ['title' => 'Комментарии']
        ],
        'actions' => [
            /*[
                'url' => '#',
                'title' => 'Добавить задачу',
                'atrs' => 'data-toggle="modal" data-target="#add_task_modal"'
            ]*/
        ]
    ])

    @include('admin.messages')

    <table id="data_table" class="table">
        <thead>
        <tr>
            <th width="50%">Сообщение</th>
            <th width="30%">Статья</th>
            <th width="10%">Автор</th>
            <th width="10%">Добавлено</th>
            <th style="width: 100px;"></th>
        </tr>
        </thead>
        <tbody>
        @foreach($comments as $comment)
            <tr>
                <td>
                    {{$comment->body}}
                </td>
                <td>
                    {{ $comment->article->title }}
                </td>
                <td>
                    <a href="{{ route('admin.users.edit', ['user' => $comment->user]) }}">{{$comment->user->name}} ({{$comment->user->email}})</a> {{ $comment->user->status ? 'активен' : 'не активен' }}
                </td>
                <td>
                    {{$comment->created_at}}
                </td>
                <td>
                    {!! Form::open([
                        'method' => 'DELETE',
                        'route' => ['admin.comments.destroy', $comment->id],
                        'style' => 'display:inline',
                        'onsubmit' => 'return confirm(\'Подтверждаете удаление?\')'
                    ]) !!}
                    {{--<div class="btn-group btn-group-sm" role="group">--}}
                    {{--<a href="{{route('admin.articles.edit', $article->id)}}" class="btn btn-primary">Редактировать</a>--}}
                    {!! Form::submit('Удалить', ['class' => 'btn btn-danger btn-sm']) !!}
                    {{--</div>--}}
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

@endsection

@section('custom-js')
    <script src="{{ asset('js/data-table.js') }}"></script>
@endsection